language: cpp
compiler:
  - gcc
  - clang
env:
  global:
  - APT_DEPENDENCIES="doxygen libltdl-dev libboost-all-dev liblog4cxx10-dev coinor-libipopt-dev libblas-dev liblapack-dev libmumps-seq-dev gfortran"
  - HOMEBREW_DEPENDENCIES="doxygen libtool boost log4cxx ipopt openblas mumps"
  - GIT_DEPENDENCIES="roboptim/roboptim-core;dev"
  - DEBSIGN_KEYID=5AE5CD75
  - PPA_URI="roboptim/ppa"
  - GH_USERNAME=thomas-moulard
  - GH_REPO=roboptim/roboptim-core-plugin-ipopt
  - LCOV_IGNORE_RULES="*tests*"
  - secure: fURGUkCIPnZZ4G+Gaf9wMPH2P8sXiDA0kA1S6qVdCbenIyilRNnLmPiqHoqwtVEl4pqpdmRoFnMbJMGIuh+61gdo23+MZ1TBeNUp86nkH4v+qVRw5n1Nm2cKJZiqiuRHcTF3jVCVgx7eUvDkPAjJ9ff4vxB8sQhOQkQeGilJyak=
  - secure: TBMOOJtRFuQK9NWIlKuBg+/LiuTa8Hz+8PsnZB/vGlc4FpoRJkz7DmnQS/sCDxunhaXZX6rac7THzCn6lrp5wksXNRRqUwRiv+JixyE1WbAnn22JBEouhs4o4fjRtwPvvkH0+EpAxuSebltCESrdxfjjkeLine4CZvV0e6HPquw=
  - secure: ALE6izEg9T+fqCBUvvhKEgOgCnR+43DSOFT/DDBIj2hCXlf9R9dQ8upaG/6JXl08i5hwVRvQMK9+zJfU25cTTM/xpC8O/5G8t7pG9Y+/QeVOMbOCQnHMDe7dB8azO8CHnC91pP00ychf8KSL2Exz+o1k1fha/9BaZZDo5zCrKKU=
  - secure: "YOeurB3pqF+B5iJHQBq4HtBoTW6PcDaNFuvDqVC64huArDZ9jjZt7EqDVEHJwuwMxrLW94lgdR9DAOwAM+X5EaMlekJ2h56not7U+553/NZYLC4MgimGOAn127kaO7CacZmdYNjQNq+G8pXJX/N+VSaqLy+WhM6Kuxts0CDC1UM="
notifications:
  hipchat:
    rooms:
    - secure: YH0AqP/y2L3+YkHNezAOfBNMB5QkeEYE3z5NV5k7gxqaEPEklQeMrSHLZzN1TuSyms/RuiQ6Zj0QA9D2ZxioTxTqGUQbh5c+Ia5n5GTIJZYg24uVXPS1w6uFQSyVNIZE6tJGpgf0RHzeGtejRW7Q9Ppr6e55TBnBc53fGTqJyPs=
  email: roboptim@googlegroups.com
branches:
  only:
  - master
  - dev
  - debian
  - travis
  - coverity_scan
script:
- export LD_LIBRARY_PATH=`pkg-config --variable=plugindir roboptim-core`:$LD_LIBRARY_PATH;
- if [ "${COVERITY_SCAN_BRANCH}" != "1" ]; then ./.travis/run build; fi
after_success: ./.travis/run after_success
after_failure: ./.travis/run after_failure
before_install:
- ./.travis/dependencies/eigen-3.2
- ./.travis/run  before_install
matrix:
  allow_failures:
    - compiler: clang
    - env: COVERITY_SCAN_BRANCH=1
    - os: osx
os:
  - linux
  - osx

addons:
  coverity_scan:
    project:
      name: "roboptim/roboptim-core-plugin-ipopt"
      description: "Build submitted via Travis CI"
    notification_email: roboptim@googlegroups.com
    build_command_prepend: ". .travis/common.sh && mkdir coverity && cd coverity && cmake .."
    build_command: "make"
    branch_pattern: coverity_scan
